# Done to increase the memory available to Gradle.
org.gradle.jvmargs = -Xmx2G
org.gradle.parallel = true

# Mod properties
mod_id = datamod_universal
mod_version = 1.0.0

mod_name = Datamod Universal
mod_description = A mostly loader-agnostic template to package resources (assets and data) as a mod jar
mod_author = ReversTeam
mod_license = MIT
display_url = https://reversteam.com
credits = Made by Tikup

# Minecraft properties
minecraft_version = 1.20.1
minecraft_version_range = [1.20.1,)
minecraft_semver_range = ~1.20.1
# (^ See https://wiki.fabricmc.net/documentation:fabric_mod_json_spec)

# Java properties
java_version = VERSION_21
java_version_number = 21

# Dependencies
fabric_version_range = >=0.18.4
fabric_version = 0.18.4
forge_version_range = [47,)
forge_version = 47.4.0
neoforge_version_range = [4,)
neoforge_version = 4.0.0